version: '3.8'

services:
  log-viewer:
    build: .
    image: laibin2886/log-viewer:latest
    container_name: log-viewer
    ports:
      - "58080:58080"
    volumes:
      - ./data:/app/data
    environment:
      - 'LISTEN_ADDR=:58080'
      - DB_PATH=/app/data/logs.db
    restart: unless-stopped
